/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new account
         * @description Create a new user account and return a fresh access token and refresh token.
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate with email and password using the OAuth2 password flow. Returns a short-lived access token and a long-lived refresh token.
         */
        post: operations["login_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate refresh token
         * @description Exchange a valid refresh token for a new access token. The refresh token itself is reused (not rotated) unless it has expired or been revoked.
         */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the supplied refresh token. The access token will continue to work until it expires naturally.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user profile
         * @description Return the profile of the currently authenticated user.
         */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all sets
         * @description Return all sets with their total printing count. When authenticated, each set also includes the number of distinct printings the user owns (`owned_count`). Unauthenticated requests receive `owned_count: null`.
         */
        get: operations["get_sets_sets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sets/{set_id}/printings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List printings in a set
         * @description Return a paginated list of printings belonging to the given set, with optional filters.
         */
        get: operations["get_set_printings_sets__set_id__printings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List cards
         * @description Return a paginated list of cards with optional filters. Each item is a card summary without printing detail.
         */
        get: operations["get_cards_cards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get card detail
         * @description Return full detail for a single card, including all printings across every set and edition.
         */
        get: operations["get_card_cards__card_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/printings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search printings across all sets
         * @description Cross-set printing search with full filter support. Unlike `GET /sets/{id}/printings`, this endpoint is not scoped to a single set and can locate a specific foiling or edition of a card regardless of which set it appears in.
         */
        get: operations["search_printings_search_printings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collection/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get owned printings
         * @description Return all printings the authenticated user owns, with full card and set detail. Use `set_id` to scope the results to a single set — useful for computing per-set completion.
         */
        get: operations["get_summary_collection_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collection/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upsert item quantity
         * @description Set an exact quantity for a single printing. Creates the ownership record if it does not exist. Setting `qty` to 0 removes the printing from the collection entirely.
         */
        post: operations["upsert_item_collection_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collection/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk update collection
         * @description Apply multiple collection actions atomically. All printing IDs are validated before any change is made — if any ID is invalid the entire request is rejected with 404.
         */
        post: operations["bulk_apply_collection_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List unowned printings
         * @description Return a paginated list of printings that exist in the catalog but are not yet owned by the authenticated user. Supports the same filters as the set printings endpoint. Typically used to build a want list or identify collection gaps.
         */
        get: operations["get_missing_missing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wishlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List wishlists
         * @description Return all wishlists belonging to the authenticated user, ordered by creation date.
         */
        get: operations["list_wishlists_wishlists_get"];
        put?: never;
        /**
         * Create a wishlist
         * @description Save a named filter as a wishlist. Free-tier users may only have **one** wishlist at a time. Delete the existing wishlist before creating a new one.
         */
        post: operations["create_wishlist_wishlists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wishlists/{wishlist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a wishlist
         * @description Permanently delete a wishlist. This frees the slot so a new wishlist can be created.
         */
        delete: operations["delete_wishlist_wishlists__wishlist_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_login_auth_token_post */
        Body_login_auth_token_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /**
         * BulkAction
         * @enum {string}
         */
        BulkAction: "set_qty" | "increment" | "mark_playset" | "clear";
        /** BulkItemRequest */
        BulkItemRequest: {
            /**
             * Printing Id
             * Format: uuid
             * @description ID of the printing to act on.
             */
            printing_id: string;
            /** @description Action to perform: 'set_qty' sets an exact quantity (requires qty); 'increment' adds 1 to the current quantity; 'mark_playset' sets quantity to 3; 'clear' removes the printing from the collection. */
            action: components["schemas"]["BulkAction"];
            /**
             * Qty
             * @description Required when action is 'set_qty'. Ignored for all other actions.
             */
            qty?: number | null;
        };
        /** BulkRequest */
        BulkRequest: {
            /**
             * Items
             * @description List of actions to apply atomically. All printing IDs must exist or the entire request is rejected.
             */
            items: components["schemas"]["BulkItemRequest"][];
        };
        /** CardDetail */
        CardDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Card Type */
            card_type: string;
            /** Hero Class */
            hero_class: string | null;
            /** Talent */
            talent: string | null;
            /** Pitch */
            pitch: number | null;
            /** Printings */
            printings: components["schemas"]["PrintingOut"][];
        };
        /** CardListItem */
        CardListItem: {
            /**
             * Id
             * Format: uuid
             * @description Unique card identifier.
             */
            id: string;
            /**
             * Name
             * @description Card name.
             */
            name: string;
            /**
             * Card Type
             * @description Card type text (e.g. 'Action', 'Attack Action — Ninja').
             */
            card_type: string;
            /**
             * Hero Class
             * @description Hero class this card belongs to (e.g. 'Ninja', 'Wizard'). Null for generic cards.
             */
            hero_class: string | null;
            /**
             * Talent
             * @description Talent affinity (e.g. 'Shadow', 'Light'). Null if the card has no talent.
             */
            talent: string | null;
            /**
             * Pitch
             * @description Pitch value (0–3). Null for cards that cannot be pitched.
             */
            pitch: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ItemResult
         * @description Result of a single collection mutation. qty=None means the row was deleted.
         */
        ItemResult: {
            /**
             * Printing Id
             * Format: uuid
             * @description ID of the affected printing.
             */
            printing_id: string;
            /**
             * Qty
             * @description Resulting quantity after the operation. Null means the row was deleted (qty reached 0).
             */
            qty: number | null;
        };
        /**
         * OwnedPrintingOut
         * @description An owned printing with full card/set detail and qty.
         */
        OwnedPrintingOut: {
            /** @description Full printing detail including card and set information. */
            printing: components["schemas"]["PrintingWithCard"];
            /**
             * Qty
             * @description Number of copies owned. Always >= 1 (rows with qty=0 are deleted).
             */
            qty: number;
        };
        /** PaginatedCards */
        PaginatedCards: {
            /**
             * Items
             * @description Cards on the current page.
             */
            items: components["schemas"]["CardListItem"][];
            /**
             * Total
             * @description Total number of cards matching the current filters.
             */
            total: number;
            /**
             * Page
             * @description Current page number (1-based).
             */
            page: number;
            /**
             * Page Size
             * @description Number of items per page.
             */
            page_size: number;
        };
        /** PaginatedPrintings */
        PaginatedPrintings: {
            /**
             * Items
             * @description Printings on the current page.
             */
            items: components["schemas"]["PrintingWithCard"][];
            /**
             * Total
             * @description Total number of printings matching the current filters.
             */
            total: number;
            /**
             * Page
             * @description Current page number (1-based).
             */
            page: number;
            /**
             * Page Size
             * @description Number of items per page.
             */
            page_size: number;
        };
        /** PrintingOut */
        PrintingOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Printing Id */
            printing_id: string;
            set: components["schemas"]["SetOut"];
            /** Edition */
            edition: string;
            /** Foiling */
            foiling: string;
            /** Rarity */
            rarity: string;
            /** Artists */
            artists: unknown[];
            /** Art Variations */
            art_variations: unknown[];
            /** Image Url */
            image_url: string | null;
            /** Tcgplayer Product Id */
            tcgplayer_product_id: string | null;
            /** Tcgplayer Url */
            tcgplayer_url: string | null;
        };
        /**
         * PrintingWithCard
         * @description Printing with nested card and set info — used in list/search endpoints.
         */
        PrintingWithCard: {
            /**
             * Id
             * Format: uuid
             * @description Unique printing identifier.
             */
            id: string;
            /**
             * Printing Id
             * @description Dataset-stable printing identifier (e.g. 'WTR000').
             */
            printing_id: string;
            /**
             * Edition
             * @description Edition code: A=Alpha, F=First, U=Unlimited, N=No specified edition.
             */
            edition: string;
            /**
             * Foiling
             * @description Foiling code: S=Standard, R=Rainbow, C=Cold, G=Gold Cold.
             */
            foiling: string;
            /**
             * Rarity
             * @description Rarity code: C=Common, R=Rare, M=Majestic, L=Legendary, F=Fabled, T=Token, P=Promo.
             */
            rarity: string;
            /**
             * Artists
             * @description List of artist names credited on this printing.
             */
            artists: unknown[];
            /**
             * Art Variations
             * @description List of art variation identifiers, if the card has alternate art in the same printing.
             */
            art_variations: unknown[];
            /**
             * Image Url
             * @description URL to the card image for this specific printing, if available.
             */
            image_url: string | null;
            /**
             * Tcgplayer Product Id
             * @description TCGplayer product ID for this printing, if available.
             */
            tcgplayer_product_id: string | null;
            /**
             * Tcgplayer Url
             * @description Direct TCGplayer listing URL for this printing, if available.
             */
            tcgplayer_url: string | null;
            /** @description The card this printing belongs to. */
            card: components["schemas"]["CardListItem"];
            /** @description The set this printing belongs to. */
            set: components["schemas"]["SetOut"];
        };
        /** RefreshRequest */
        RefreshRequest: {
            /**
             * Refresh Token
             * @description Opaque refresh token previously issued by this API.
             */
            refresh_token: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** SetOut */
        SetOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Image Url */
            image_url: string | null;
            /** Set Type */
            set_type: string;
        };
        /**
         * SetSummary
         * @description Set with aggregate counts; owned_count is None when unauthenticated.
         */
        SetSummary: {
            /**
             * Id
             * Format: uuid
             * @description Unique set identifier.
             */
            id: string;
            /**
             * Code
             * @description Short set code (e.g. 'WTR', 'ARC').
             */
            code: string;
            /**
             * Name
             * @description Full set name (e.g. 'Welcome to Rathe').
             */
            name: string;
            /**
             * Image Url
             * @description URL to the set's logo or key art, if available.
             */
            image_url: string | null;
            /**
             * Set Type
             * @description Category: booster, deck, or promo.
             */
            set_type: string;
            /**
             * Printing Count
             * @description Total number of distinct printings (card x edition x foiling) in this set.
             */
            printing_count: number;
            /**
             * Owned Count
             * @description Number of those printings the authenticated user owns at least one copy of. Null when the request is unauthenticated.
             */
            owned_count: number | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /**
             * Access Token
             * @description Short-lived JWT (15 min). Send as 'Authorization: Bearer <token>'.
             */
            access_token: string;
            /**
             * Token Type
             * @description Always 'bearer'.
             * @default bearer
             */
            token_type: string;
            /**
             * Refresh Token
             * @description Opaque long-lived token. Use with POST /auth/refresh to obtain a new access token.
             */
            refresh_token: string;
        };
        /** UpsertItemRequest */
        UpsertItemRequest: {
            /**
             * Printing Id
             * Format: uuid
             * @description ID of the printing to update.
             */
            printing_id: string;
            /**
             * Qty
             * @description Desired quantity. Set to 0 to remove the printing from the collection.
             */
            qty: number;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             * @description Unique user identifier.
             */
            id: string;
            /**
             * Email
             * @description The user's email address.
             */
            email: string;
            /**
             * Is Active
             * @description False if the account has been disabled by an administrator.
             */
            is_active: boolean;
            /**
             * Is Admin
             * @description True if the user has administrative privileges.
             */
            is_admin: boolean;
            /**
             * Created At
             * Format: date-time
             * @description UTC timestamp when the account was created.
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WishlistCreate */
        WishlistCreate: {
            /**
             * Name
             * @description Display name for the wishlist.
             */
            name: string;
            /** @description Filter criteria that define which missing printings this wishlist tracks. */
            filter_json?: components["schemas"]["WishlistFilter"];
        };
        /** WishlistFilter */
        WishlistFilter: {
            /**
             * Card Id
             * @description Scope to printings of a specific card.
             */
            card_id?: string | null;
            /**
             * Set Id
             * @description Scope to printings in a specific set.
             */
            set_id?: string | null;
            /**
             * Edition
             * @description Edition code: A=Alpha, F=First, U=Unlimited, N=No specified edition.
             */
            edition?: string | null;
            /**
             * Foiling
             * @description Foiling code: S=Standard, R=Rainbow, C=Cold, G=Gold Cold.
             */
            foiling?: string | null;
            /**
             * Rarity
             * @description Exact rarity code: C=Common, R=Rare, M=Majestic, L=Legendary, F=Fabled, T=Token, P=Promo.
             */
            rarity?: string | null;
            /**
             * Artists
             * @description Substring match against the artists array (case-insensitive).
             */
            artists?: string | null;
        };
        /** WishlistOut */
        WishlistOut: {
            /**
             * Id
             * Format: uuid
             * @description Unique wishlist identifier.
             */
            id: string;
            /**
             * Name
             * @description Display name for the wishlist.
             */
            name: string;
            /** @description Saved filter criteria. */
            filter_json: components["schemas"]["WishlistFilter"];
            /**
             * Created At
             * Format: date-time
             * @description UTC timestamp when the wishlist was created.
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description UTC timestamp of the last update.
             */
            updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description A user with that email address already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_auth_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Incorrect email or password. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Account has been disabled. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Refresh token is invalid, expired, or has been revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    get_sets_sets_get: {
        parameters: {
            query?: {
                /** @description Filter by category: booster, deck, or promo. */
                set_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_set_printings_sets__set_id__printings_get: {
        parameters: {
            query?: {
                /** @description Partial card name search (case-insensitive). */
                q?: string | null;
                /** @description Exact rarity code: C=Common, R=Rare, M=Majestic, L=Legendary, F=Fabled, T=Token, P=Promo. */
                rarity?: string | null;
                /** @description Foiling code: S=Standard, R=Rainbow, C=Cold, G=Gold Cold. */
                foiling?: string | null;
                /** @description Edition code: A=Alpha, F=First, U=Unlimited, N=No specified edition. */
                edition?: string | null;
                /** @description Filter by hero class (e.g. Ninja, Wizard). */
                hero_class?: string | null;
                /** @description Filter by talent (e.g. Shadow, Light). */
                talent?: string | null;
                /** @description Partial match on card type text (e.g. 'Attack Action'). */
                card_type?: string | null;
                /** @description Page number (1-based). */
                page?: number;
                /** @description Number of results per page (max 100). */
                page_size?: number;
            };
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPrintings"];
                };
            };
            /** @description Set not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cards_cards_get: {
        parameters: {
            query?: {
                /** @description Partial name search (case-insensitive). */
                name?: string | null;
                /** @description Filter by hero class (e.g. Ninja, Wizard). */
                hero_class?: string | null;
                /** @description Filter by talent (e.g. Shadow, Light). */
                talent?: string | null;
                /** @description Filter by exact pitch value (0–3). */
                pitch?: number | null;
                /** @description Filter to cards that appear in a specific set by set code. */
                set_code?: string | null;
                /** @description Page number (1-based). */
                page?: number;
                /** @description Number of results per page (max 100). */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCards"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_card_cards__card_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardDetail"];
                };
            };
            /** @description Card not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_printings_search_printings_get: {
        parameters: {
            query?: {
                /** @description Partial card name search (case-insensitive). */
                q?: string | null;
                /** @description Exact rarity code: C=Common, R=Rare, M=Majestic, L=Legendary, F=Fabled, T=Token, P=Promo. */
                rarity?: string | null;
                /** @description Foiling code: S=Standard, R=Rainbow, C=Cold, G=Gold Cold. */
                foiling?: string | null;
                /** @description Edition code: A=Alpha, F=First, U=Unlimited, N=No specified edition. */
                edition?: string | null;
                /** @description Filter by hero class (e.g. Ninja, Wizard). */
                hero_class?: string | null;
                /** @description Filter by talent (e.g. Shadow, Light). */
                talent?: string | null;
                /** @description Partial match on card type text (e.g. 'Attack Action'). */
                card_type?: string | null;
                /** @description Filter to a specific set by set code (e.g. 'WTR'). */
                set_code?: string | null;
                /** @description Page number (1-based). */
                page?: number;
                /** @description Number of results per page (max 100). */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPrintings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_collection_summary_get: {
        parameters: {
            query?: {
                /** @description Scope results to a specific set. */
                set_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnedPrintingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_item_collection_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResult"];
                };
            };
            /** @description Printing not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_apply_collection_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResult"][];
                };
            };
            /** @description One or more printing IDs were not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_missing_missing_get: {
        parameters: {
            query?: {
                /** @description Scope to printings in a specific set. */
                set_id?: string | null;
                /** @description Scope to printings of a specific card. */
                card_id?: string | null;
                /** @description Edition code: A=Alpha, F=First, U=Unlimited, N=No specified edition. */
                edition?: string | null;
                /** @description Foiling code: S=Standard, R=Rainbow, C=Cold, G=Gold Cold. */
                foiling?: string | null;
                /** @description Exact rarity code: C=Common, R=Rare, M=Majestic, L=Legendary, F=Fabled, T=Token, P=Promo. */
                rarity?: string | null;
                /** @description Substring match against the artists array (case-insensitive). */
                artists?: string | null;
                /** @description Page number (1-based). */
                page?: number;
                /** @description Number of results per page (max 100). */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPrintings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_wishlists_wishlists_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WishlistOut"][];
                };
            };
        };
    };
    create_wishlist_wishlists_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WishlistCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WishlistOut"];
                };
            };
            /** @description Free-tier limit reached — delete the existing wishlist first. */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_wishlist_wishlists__wishlist_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wishlist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wishlist not found or belongs to a different user. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
