"""drop collection_mode from users

Revision ID: 1f00615bc51f
Revises: a1b2c3d4e5f6
Create Date: 2026-03-15 19:42:35.506974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f00615bc51f'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'collection_mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('collection_mode', sa.VARCHAR(length=16), server_default=sa.text("'playset'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
