"""strategy_b_printing_model

Revision ID: 466cdde84c13
Revises: 46b8751de304
Create Date: 2026-02-24 00:43:51.282567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '466cdde84c13'
down_revision: Union[str, Sequence[str], None] = '46b8751de304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('source_id', sa.String(length=21), nullable=True))
    op.add_column('cards', sa.Column('pitch', sa.Integer(), nullable=True))
    op.alter_column('cards', 'card_type',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_cards_pitch'), 'cards', ['pitch'], unique=False)
    op.create_index(op.f('ix_cards_source_id'), 'cards', ['source_id'], unique=True)
    op.drop_constraint(op.f('uq_owned_printing'), 'owned_printings', type_='unique')
    op.create_unique_constraint('uq_owned_printing', 'owned_printings', ['user_id', 'printing_id'])
    op.drop_column('owned_printings', 'foil_type')
    # Add with server_default so existing rows get a valid value before NOT NULL is enforced
    op.add_column('printings', sa.Column('edition', sa.String(length=4), nullable=False, server_default='N'))
    op.add_column('printings', sa.Column('foiling', sa.String(length=4), nullable=False, server_default='S'))
    op.add_column('printings', sa.Column('artists', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('printings', sa.Column('art_variations', sa.JSON(), nullable=False, server_default='[]'))
    # Remove server defaults — the application always supplies these values
    op.alter_column('printings', 'edition', server_default=None)
    op.alter_column('printings', 'foiling', server_default=None)
    op.alter_column('printings', 'artists', server_default=None)
    op.alter_column('printings', 'art_variations', server_default=None)
    op.add_column('printings', sa.Column('tcgplayer_product_id', sa.String(length=100), nullable=True))
    op.add_column('printings', sa.Column('tcgplayer_url', sa.Text(), nullable=True))
    op.drop_column('printings', 'foil_types')
    op.drop_column('printings', 'is_promo')
    op.add_column('sets', sa.Column('source_id', sa.String(length=21), nullable=True))
    op.drop_column('sets', 'edition')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets', sa.Column('edition', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('sets', 'source_id')
    op.add_column('printings', sa.Column('is_promo', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('printings', sa.Column('foil_types', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('printings', 'tcgplayer_url')
    op.drop_column('printings', 'tcgplayer_product_id')
    op.drop_column('printings', 'art_variations')
    op.drop_column('printings', 'artists')
    op.drop_column('printings', 'foiling')
    op.drop_column('printings', 'edition')
    op.add_column('owned_printings', sa.Column('foil_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_constraint('uq_owned_printing', 'owned_printings', type_='unique')
    op.create_unique_constraint(op.f('uq_owned_printing'), 'owned_printings', ['user_id', 'printing_id', 'foil_type'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_cards_source_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_pitch'), table_name='cards')
    op.alter_column('cards', 'card_type',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_column('cards', 'pitch')
    op.drop_column('cards', 'source_id')
    # ### end Alembic commands ###
