"""add set_type column

Revision ID: 977f7b0dd66e
Revises: 466cdde84c13
Create Date: 2026-03-13 15:42:55.675179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '977f7b0dd66e'
down_revision: Union[str, Sequence[str], None] = '466cdde84c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets', sa.Column('set_type', sa.String(length=16), nullable=False, server_default='booster'))
    op.create_index(op.f('ix_sets_set_type'), 'sets', ['set_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sets_set_type'), table_name='sets')
    op.drop_column('sets', 'set_type')
    # ### end Alembic commands ###
