"""initial_schema

Revision ID: ae07868a7538
Revises: 
Create Date: 2026-02-23 00:13:31.683572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae07868a7538'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('card_type', sa.String(length=64), nullable=False),
    sa.Column('hero_class', sa.String(length=64), nullable=True),
    sa.Column('talent', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_card_type'), 'cards', ['card_type'], unique=False)
    op.create_index(op.f('ix_cards_hero_class'), 'cards', ['hero_class'], unique=False)
    op.create_index(op.f('ix_cards_name'), 'cards', ['name'], unique=False)
    op.create_index(op.f('ix_cards_talent'), 'cards', ['talent'], unique=False)
    op.create_table('sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('edition', sa.String(length=64), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sets_code'), 'sets', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('printings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('printing_id', sa.String(length=64), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('set_id', sa.UUID(), nullable=False),
    sa.Column('rarity', sa.String(length=32), nullable=False),
    sa.Column('foil_types', sa.JSON(), nullable=False),
    sa.Column('is_promo', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_printings_card_id'), 'printings', ['card_id'], unique=False)
    op.create_index(op.f('ix_printings_printing_id'), 'printings', ['printing_id'], unique=True)
    op.create_index(op.f('ix_printings_rarity'), 'printings', ['rarity'], unique=False)
    op.create_index(op.f('ix_printings_set_id'), 'printings', ['set_id'], unique=False)
    op.create_table('wishlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('filter_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wishlists_user_id'), 'wishlists', ['user_id'], unique=False)
    op.create_table('owned_printings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('printing_id', sa.UUID(), nullable=False),
    sa.Column('foil_type', sa.String(length=32), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('qty >= 1', name='ck_owned_printing_qty_positive'),
    sa.ForeignKeyConstraint(['printing_id'], ['printings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'printing_id', 'foil_type', name='uq_owned_printing')
    )
    op.create_index(op.f('ix_owned_printings_printing_id'), 'owned_printings', ['printing_id'], unique=False)
    op.create_index(op.f('ix_owned_printings_user_id'), 'owned_printings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_owned_printings_user_id'), table_name='owned_printings')
    op.drop_index(op.f('ix_owned_printings_printing_id'), table_name='owned_printings')
    op.drop_table('owned_printings')
    op.drop_index(op.f('ix_wishlists_user_id'), table_name='wishlists')
    op.drop_table('wishlists')
    op.drop_index(op.f('ix_printings_set_id'), table_name='printings')
    op.drop_index(op.f('ix_printings_rarity'), table_name='printings')
    op.drop_index(op.f('ix_printings_printing_id'), table_name='printings')
    op.drop_index(op.f('ix_printings_card_id'), table_name='printings')
    op.drop_table('printings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sets_code'), table_name='sets')
    op.drop_table('sets')
    op.drop_index(op.f('ix_cards_talent'), table_name='cards')
    op.drop_index(op.f('ix_cards_name'), table_name='cards')
    op.drop_index(op.f('ix_cards_hero_class'), table_name='cards')
    op.drop_index(op.f('ix_cards_card_type'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
